service: wedev-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: default
  stage: api
  apiName: wedev-api

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - README.md

functions:
  index:
    name: wedev-api
    handler: dist/src/index.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          path: '{proxy+}'
          method: any
          cors: true
